### ISSUE TITLE
Build instructions are missing

### ISSUE THREAD

**Issue by rurban** [garnetius/JSONg#1]
There's no Makefile or CMakeLists.txt neither for this not for it's two dependencies.

Calling quantum a library is a stretch, currently it's a snippet collection. It looks like it needs to be copied to `include/quantum` or included from the download location. Similar for ultraviolet.
Manual compilation works neither. quantum's include uchar.h is broken.

**Comment by garnetius** [comment]
> There's no Makefile or CMakeLists.txt neither for this not for it's two dependencies.

I do not have time currently to add support for various build systems, but I definitely plan to do so.

Jsong comes with [five test applications](https://github.com/garnetius/Jsong/tree/master/apps) which currently have build shell scripts for Windows. You can check them out and see what include paths look like and what defines you need to build a particular parser version.

If you have time, you are invited to turn these into CMakeLists.txt and submit a pull request.

> Calling quantum a library is a stretch, currently it's a snippet collection

Off-topic (it's a Jsong issue tracker), subjective, and kind of rude even? It's a library of headers mostly, but nothing stops you from including what you need from there and turning this into a shared object or a DLL. I don't know, other header-only projects don't have any problem calling themselves "libraries", but me doing that somehow pissed you off? "Snippet collection". OK.

> Manual compilation works neither. quantum's include uchar.h is broken.

Let's assume for a moment that you didn't see [this folder](https://github.com/garnetius/Jsong/tree/master/apps) full of build scripts. I need to build and use Jsong somehow myself because I had to benchmark it after all. So the problem might be due to incorrect flags that you pass to your compiler?

I understand Windows build scripts are awkward and I could at least provide UNIX build scripts, but there are other priorities right now, and I will add support for CMake once I can.

**Comment by garnetius** [comment]
Commit https://github.com/garnetius/JSONg/commit/552efa2b54191951696d6e98170f8569793c1e45 introduced major improvements to code base along with complete CMake build system and stabilized USON format.

It is now also possible to use JSONg without even building it at all. Refer to [bench.c](https://github.com/garnetius/JSONg/blob/master/testsuite/bench.c) program from its test suite to see how it's done: just use JSONg parsing templates directly with appropriate parameters.
